version: '2'
services:
mongo:
    container_name: mongo1
    image: "mongo:latest"
    ports:
    - "27017:27017"
mongo:
    container_name: mongo2
    image: "mongo:latest"
    ports:
    - "27018:27017"
mongo:
    container_name: mongo3
    image: "mongo:latest"
    ports:
    - "27019:27017"
redis:
    container_name: redis
    image: "redis:latest"
